// Code generated by reset generator. DO NOT EDIT.

package models

import (
	"github.com/google/uuid"
)

// Reset сбрасывает состояние объекта URL к начальным значениям.
func (r *URL) Reset() {
	r.ID = ""
	r.Original = ""
	r.CreatorID = uuid.Nil
	r.IsDeleted = false
}

// Reset сбрасывает состояние объекта DeletableURL к начальным значениям.
func (r *DeletableURL) Reset() {
	r.ID = ""
	r.CreatorID = uuid.Nil
}

// Reset сбрасывает состояние объекта ShortenRequest к начальным значениям.
func (r *ShortenRequest) Reset() {
	r.URL = ""
}

// Reset сбрасывает состояние объекта ShortenResponse к начальным значениям.
func (r *ShortenResponse) Reset() {
	r.Result = ""
}

// Reset сбрасывает состояние объекта ShortenBatchRequest к начальным значениям.
func (r *ShortenBatchRequest) Reset() {
	r.CorrelationID = ""
	r.OriginalURL = ""
}

// Reset сбрасывает состояние объекта ShortenBatchResponse к начальным значениям.
func (r *ShortenBatchResponse) Reset() {
	r.CorrelationID = ""
	r.ShortURL = ""
}

// Reset сбрасывает состояние объекта GetUserUrlsResponseItem к начальным значениям.
func (r *GetUserUrlsResponseItem) Reset() {
	r.ShortURL = ""
	r.OriginalURL = ""
}

// Reset сбрасывает состояние объекта Event к начальным значениям.
func (r *Event) Reset() {
	r.Timestamp = 0
	r.Action = ""
	r.UserID = ""
	r.OriginalURL = ""
}
