// Code generated by reset generator. DO NOT EDIT.

package repository

import (
	"os"
	"sync"
)

// Reset сбрасывает состояние объекта File к начальным значениям.
func (r *File) Reset() {
	r.mu = sync.RWMutex{}
	clear(r.urlsCache)
	clear(r.userUrlsCache)
	if r.file != nil {
		*r.file = os.File{}
	}
	r.queue = nil
	r.shutdown = nil
	r.wg = sync.WaitGroup{}
}

// Reset сбрасывает состояние объекта Memory к начальным значениям.
func (r *Memory) Reset() {
	r.mu = sync.RWMutex{}
	clear(r.urls)
	clear(r.userURLs)
}
