package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/pkg/errors"
	"golang.org/x/tools/imports"
)

const outputFileName = "reset.gen.go"

// FileInfo содержит информацию о файле для генерации
type FileInfo struct {
	PackageName string
	Imports     []string
	Structs     []StructInfo
}

// StructInfo содержит информацию о структуре для генерации
type StructInfo struct {
	StructName string
	Fields     []FieldInfo
}

// FieldInfo содержит информацию о поле структуры
type FieldInfo struct {
	FieldName string
	TypeInfo  *TypeInfo
}

// TypeInfo содержит расширенную информацию о типе
type TypeInfo struct {
	IsBasic        bool
	IsStruct       bool
	IsInterface    bool
	IsMap          bool
	IsSlice        bool
	IsPointer      bool
	IsUUID         bool
	IsChan         bool
	UnderlyingType string
	ElemType       string
	TypeString     string
	Direction      ast.ChanDir
}

const resetTemplate = `// Code generated by reset generator. DO NOT EDIT.

package {{.PackageName}}

{{- if .Imports}}
import (
{{- range .Imports}}
	{{.}}
{{- end}}
)
{{- end}}

{{range .Structs}}
// Reset сбрасывает состояние объекта {{.StructName}} к начальным значениям.
func (r *{{.StructName}}) Reset() {
	{{- range .Fields }}
		{{resetExpr "r" .FieldName .TypeInfo}}
	{{- end}}
}
{{end}}
`

func main() {
	root := "."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}

	filesByPackage := make(map[string]FileInfo)
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() ||
			!strings.HasSuffix(path, ".go") ||
			strings.HasSuffix(path, "_test.go") ||
			strings.HasSuffix(path, outputFileName) {
			return nil
		}

		file, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.ParseComments)
		if err != nil {
			log.Printf("Failed to parse file: %v\n", err)

		}

		fileInfo := inspectFile(file)

		if len(fileInfo.Structs) > 0 {
			pkgPath := filepath.Dir(path)
			if fInfo, ok := filesByPackage[pkgPath]; !ok {
				filesByPackage[pkgPath] = fileInfo
			} else {
				fInfo.Structs = append(fInfo.Structs, fileInfo.Structs...)
				fInfo.Imports = append(fInfo.Imports, fileInfo.Imports...)
				filesByPackage[pkgPath] = fInfo
			}
		}

		return nil
	})
	if err != nil {
		log.Printf("Walk dir error: %v\n", err)
		return
	}

	for pkgPath, fileInfo := range filesByPackage {
		if err = generateFile(pkgPath, fileInfo); err != nil {
			log.Printf("Failed to generate reset file for package %s: %v\n", pkgPath, err)
		}
	}
}

func inspectFile(file *ast.File) FileInfo {
	fileInfo := FileInfo{
		PackageName: file.Name.Name,
	}

	for _, d := range file.Decls {
		genDecl, ok := d.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		if genDecl.Doc == nil {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			if structInfo, found := inspectComments(genDecl, typeSpec, structType); found {
				fileInfo.Structs = append(fileInfo.Structs, structInfo)
			}
		}
	}

	fileInfo.Imports = make([]string, 0, len(file.Imports))
	for _, imp := range file.Imports {
		fileInfo.Imports = append(fileInfo.Imports, imp.Path.Value)
	}

	return fileInfo
}

func inspectComments(
	genDecl *ast.GenDecl, typeSpec *ast.TypeSpec, structType *ast.StructType,
) (StructInfo, bool) {
	structInfo := StructInfo{
		StructName: typeSpec.Name.Name,
		Fields:     make([]FieldInfo, 0, len(structType.Fields.List)),
	}

	for _, comment := range genDecl.Doc.List {
		if strings.TrimSpace(comment.Text) != "// generate:reset" {
			continue
		}

		for _, field := range structType.Fields.List {
			typeInfo := analyzeType(field.Type)

			// определяем имя поля
			var fieldName string
			if len(field.Names) > 0 {
				fieldName = field.Names[0].Name
			} else {
				// embedded поле - используем имя типа
				if ident, ok := field.Type.(*ast.Ident); ok {
					fieldName = ident.Name
				} else if selector, ok := field.Type.(*ast.SelectorExpr); ok {
					if x, ok := selector.X.(*ast.Ident); ok {
						fieldName = x.Name + "." + selector.Sel.Name
					}
				}
			}

			if fieldName != "" {
				structInfo.Fields = append(structInfo.Fields, FieldInfo{
					FieldName: fieldName,
					TypeInfo:  typeInfo,
				})
			}
		}

		return structInfo, true
	}

	return structInfo, false
}

func analyzeType(expr ast.Expr) *TypeInfo {
	info := &TypeInfo{}

	switch t := expr.(type) {
	case *ast.Ident:
		info.TypeString = t.Name

		// проверяем базовые типы
		switch t.Name {
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"uintptr", "byte", "rune", "float32", "float64",
			"string", "bool":
			info.IsBasic = true
			info.UnderlyingType = t.Name
			return info
		}

		// проверяем кастомные типы
		if t.Obj != nil && t.Obj.Decl != nil {
			if typeSpec, ok := t.Obj.Decl.(*ast.TypeSpec); ok {
				if ident, ok := typeSpec.Type.(*ast.Ident); ok {
					info.IsBasic = true
					info.UnderlyingType = ident.Name
					return info
				}
				if _, ok := typeSpec.Type.(*ast.InterfaceType); ok {
					info.IsInterface = true
					return info
				}
			}
		}

	case *ast.SelectorExpr:
		// обработка UUID
		if x, ok := t.X.(*ast.Ident); ok {
			info.TypeString = x.Name + "." + t.Sel.Name

			if x.Name == "uuid" && t.Sel.Name == "UUID" {
				info.IsUUID = true
			}
		}

	case *ast.StarExpr:
		info.IsPointer = true
		// рекурсивно анализируем тип под указателем
		elemInfo := analyzeType(t.X)
		info.ElemType = elemInfo.TypeString
		info.IsStruct = elemInfo.IsStruct
		info.IsBasic = elemInfo.IsBasic
		info.IsUUID = elemInfo.IsUUID
		info.UnderlyingType = elemInfo.UnderlyingType

	case *ast.ArrayType:
		info.IsSlice = true
		elemInfo := analyzeType(t.Elt)
		info.ElemType = elemInfo.TypeString

	case *ast.MapType:
		info.IsMap = true

	case *ast.StructType:
		info.IsStruct = true
		info.TypeString = "struct"

	case *ast.InterfaceType:
		info.IsInterface = true
		info.TypeString = "interface{}"
	case *ast.ChanType:
		info.IsChan = true
		info.Direction = t.Dir
		valueInfo := analyzeType(t.Value)
		info.ElemType = valueInfo.TypeString

		switch t.Dir {
		case ast.SEND:
			info.TypeString = "chan<- " + valueInfo.TypeString
		case ast.RECV:
			info.TypeString = "<-chan " + valueInfo.TypeString
		default:
			info.TypeString = "chan " + valueInfo.TypeString
		}
	}

	return info
}

func resetExpr(receiver, fieldName string, typeInfo *TypeInfo) string {
	switch {
	case typeInfo.IsInterface:
		return fmt.Sprintf(
			`if resetter, ok := %s.%s.(interface{ Reset() }); ok && %s.%s != nil {
				resetter.Reset()
			} else {
				%s.%s = nil
			}`, receiver, fieldName, receiver, fieldName, receiver, fieldName,
		)

	case typeInfo.IsStruct:
		return fmt.Sprintf(`
			if resetter, ok := interface{}(&%s.%s).(interface{ Reset() }); ok {
				resetter.Reset()
			} else {
				%s.%s = %s{}
			}`,
			receiver, fieldName, receiver, fieldName, typeInfo.TypeString,
		)

	case typeInfo.IsPointer:
		return resetPointer(receiver, fieldName, typeInfo)

	case typeInfo.IsMap:
		return fmt.Sprintf("clear(%s.%s)", receiver, fieldName)

	case typeInfo.IsChan:
		return fmt.Sprintf("%s.%s = nil", receiver, fieldName)

	case typeInfo.IsSlice:
		return fmt.Sprintf(`
			if %s.%s != nil {
				%s.%s = %s.%s[:0]
			}`,
			receiver, fieldName, receiver, fieldName, receiver, fieldName,
		)

	case typeInfo.IsUUID:
		return fmt.Sprintf("%s.%s = uuid.Nil", receiver, fieldName)

	case typeInfo.IsBasic:
		switch typeInfo.UnderlyingType {
		case "string":
			return fmt.Sprintf(`%s.%s = ""`, receiver, fieldName)
		case "bool":
			return fmt.Sprintf("%s.%s = false", receiver, fieldName)
		case "float32", "float64":
			return fmt.Sprintf("%s.%s = 0.0", receiver, fieldName)
		default:
			return fmt.Sprintf("%s.%s = 0", receiver, fieldName)
		}

	default:
		return fmt.Sprintf("%s.%s = %s{}", receiver, fieldName, typeInfo.TypeString)
	}
}

func resetPointer(receiver, fieldName string, typeInfo *TypeInfo) string {
	switch {
	case typeInfo.IsStruct:
		return fmt.Sprintf(
			`if %s.%s != nil {
				if resetter, ok := interface{}(%s.%s).(interface{ Reset() }); ok {
					resetter.Reset()
				} else {
					*%s.%s = %s{}
				}
			}`,
			receiver, fieldName, receiver, fieldName, receiver, fieldName, typeInfo.ElemType,
		)

	case typeInfo.IsBasic:
		return fmt.Sprintf(
			`if %s.%s != nil {
				*%s.%s = %s(0)
			}`,
			receiver, fieldName, receiver, fieldName, typeInfo.UnderlyingType,
		)

	default:
		return fmt.Sprintf(
			`if %s.%s != nil {
				*%s.%s = %s{}
			}`,
			receiver, fieldName, receiver, fieldName, typeInfo.ElemType,
		)
	}
}

func generateFile(pkgPath string, fileInfo FileInfo) error {
	if len(fileInfo.Structs) == 0 {
		log.Println("There no structs in package ", pkgPath)
		return nil
	}

	// создаем шаблон
	tmpl, err := template.New("reset").Funcs(template.FuncMap{
		"resetExpr": func(receiver, fieldName string, typeInfo *TypeInfo) string {
			return resetExpr(receiver, fieldName, typeInfo)
		},
	}).Parse(resetTemplate)
	if err != nil {
		return errors.Wrap(err, "tamplate parse")
	}

	// генерируем код
	var buf bytes.Buffer
	if err = tmpl.Execute(&buf, fileInfo); err != nil {
		return errors.Wrap(err, "template execute")
	}

	filePath := filepath.Join(pkgPath, "reset.gen.go")

	// imports.Process для форматирования и удаления неиспользуемых импортов
	processed, err := imports.Process(filePath, buf.Bytes(), &imports.Options{
		Comments:   true,
		TabIndent:  true,
		TabWidth:   4,
		FormatOnly: false, // удалять неиспользуемые импорты
	})
	if err != nil {
		return errors.Wrap(err, "process imports")
	}

	err = os.WriteFile(filePath, processed, 0644)
	return errors.Wrap(err, "write file")
}
