// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/proto/shortener.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type URLShortenRequest struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Url string                 `protobuf:"bytes,1,opt,name=url,proto3"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *URLShortenRequest) Reset() {
	*x = URLShortenRequest{}
	mi := &file_api_proto_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLShortenRequest) ProtoMessage() {}

func (x *URLShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *URLShortenRequest) GetUrl() string {
	if x != nil {
		return x.xxx_hidden_Url
	}
	return ""
}

func (x *URLShortenRequest) SetUrl(v string) {
	x.xxx_hidden_Url = v
}

type URLShortenRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Url string
}

func (b0 URLShortenRequest_builder) Build() *URLShortenRequest {
	m0 := &URLShortenRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Url = b.Url
	return m0
}

type URLShortenResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Result string                 `protobuf:"bytes,1,opt,name=result,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *URLShortenResponse) Reset() {
	*x = URLShortenResponse{}
	mi := &file_api_proto_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLShortenResponse) ProtoMessage() {}

func (x *URLShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *URLShortenResponse) GetResult() string {
	if x != nil {
		return x.xxx_hidden_Result
	}
	return ""
}

func (x *URLShortenResponse) SetResult(v string) {
	x.xxx_hidden_Result = v
}

type URLShortenResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Result string
}

func (b0 URLShortenResponse_builder) Build() *URLShortenResponse {
	m0 := &URLShortenResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Result = b.Result
	return m0
}

type URLExpandRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLExpandRequest) Reset() {
	*x = URLExpandRequest{}
	mi := &file_api_proto_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLExpandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLExpandRequest) ProtoMessage() {}

func (x *URLExpandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *URLExpandRequest) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *URLExpandRequest) SetId(v string) {
	x.xxx_hidden_Id = v
}

type URLExpandRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 URLExpandRequest_builder) Build() *URLExpandRequest {
	m0 := &URLExpandRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type URLExpandResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Result string                 `protobuf:"bytes,1,opt,name=result,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *URLExpandResponse) Reset() {
	*x = URLExpandResponse{}
	mi := &file_api_proto_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLExpandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLExpandResponse) ProtoMessage() {}

func (x *URLExpandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *URLExpandResponse) GetResult() string {
	if x != nil {
		return x.xxx_hidden_Result
	}
	return ""
}

func (x *URLExpandResponse) SetResult(v string) {
	x.xxx_hidden_Result = v
}

type URLExpandResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Result string
}

func (b0 URLExpandResponse_builder) Build() *URLExpandResponse {
	m0 := &URLExpandResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Result = b.Result
	return m0
}

type UserURLsResponse struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Url *[]*URLData            `protobuf:"bytes,1,rep,name=url,proto3"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserURLsResponse) Reset() {
	*x = UserURLsResponse{}
	mi := &file_api_proto_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURLsResponse) ProtoMessage() {}

func (x *UserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserURLsResponse) GetUrl() []*URLData {
	if x != nil {
		if x.xxx_hidden_Url != nil {
			return *x.xxx_hidden_Url
		}
	}
	return nil
}

func (x *UserURLsResponse) SetUrl(v []*URLData) {
	x.xxx_hidden_Url = &v
}

type UserURLsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Url []*URLData
}

func (b0 UserURLsResponse_builder) Build() *UserURLsResponse {
	m0 := &UserURLsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Url = &b.Url
	return m0
}

type URLData struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ShortUrl    string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3"`
	xxx_hidden_OriginalUrl string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *URLData) Reset() {
	*x = URLData{}
	mi := &file_api_proto_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLData) ProtoMessage() {}

func (x *URLData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *URLData) GetShortUrl() string {
	if x != nil {
		return x.xxx_hidden_ShortUrl
	}
	return ""
}

func (x *URLData) GetOriginalUrl() string {
	if x != nil {
		return x.xxx_hidden_OriginalUrl
	}
	return ""
}

func (x *URLData) SetShortUrl(v string) {
	x.xxx_hidden_ShortUrl = v
}

func (x *URLData) SetOriginalUrl(v string) {
	x.xxx_hidden_OriginalUrl = v
}

type URLData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ShortUrl    string
	OriginalUrl string
}

func (b0 URLData_builder) Build() *URLData {
	m0 := &URLData{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ShortUrl = b.ShortUrl
	x.xxx_hidden_OriginalUrl = b.OriginalUrl
	return m0
}

var File_api_proto_shortener_proto protoreflect.FileDescriptor

const file_api_proto_shortener_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/shortener.proto\x1a\x1bgoogle/protobuf/empty.proto\"%\n" +
	"\x11URLShortenRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\",\n" +
	"\x12URLShortenResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\"\n" +
	"\x10URLExpandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x11URLExpandResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\".\n" +
	"\x10UserURLsResponse\x12\x1a\n" +
	"\x03url\x18\x01 \x03(\v2\b.URLDataR\x03url\"I\n" +
	"\aURLData\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl2\xb8\x01\n" +
	"\x10ShortenerService\x125\n" +
	"\n" +
	"ShortenURL\x12\x12.URLShortenRequest\x1a\x13.URLShortenResponse\x122\n" +
	"\tExpandURL\x12\x11.URLExpandRequest\x1a\x12.URLExpandResponse\x129\n" +
	"\fListUserURLs\x12\x16.google.protobuf.Empty\x1a\x11.UserURLsResponseB8Z6github.com/dsnikitin/shortener/internal/grpc/api/protob\x06proto3"

var file_api_proto_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_shortener_proto_goTypes = []any{
	(*URLShortenRequest)(nil),  // 0: URLShortenRequest
	(*URLShortenResponse)(nil), // 1: URLShortenResponse
	(*URLExpandRequest)(nil),   // 2: URLExpandRequest
	(*URLExpandResponse)(nil),  // 3: URLExpandResponse
	(*UserURLsResponse)(nil),   // 4: UserURLsResponse
	(*URLData)(nil),            // 5: URLData
	(*emptypb.Empty)(nil),      // 6: google.protobuf.Empty
}
var file_api_proto_shortener_proto_depIdxs = []int32{
	5, // 0: UserURLsResponse.url:type_name -> URLData
	0, // 1: ShortenerService.ShortenURL:input_type -> URLShortenRequest
	2, // 2: ShortenerService.ExpandURL:input_type -> URLExpandRequest
	6, // 3: ShortenerService.ListUserURLs:input_type -> google.protobuf.Empty
	1, // 4: ShortenerService.ShortenURL:output_type -> URLShortenResponse
	3, // 5: ShortenerService.ExpandURL:output_type -> URLExpandResponse
	4, // 6: ShortenerService.ListUserURLs:output_type -> UserURLsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_shortener_proto_init() }
func file_api_proto_shortener_proto_init() {
	if File_api_proto_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_shortener_proto_rawDesc), len(file_api_proto_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_shortener_proto_goTypes,
		DependencyIndexes: file_api_proto_shortener_proto_depIdxs,
		MessageInfos:      file_api_proto_shortener_proto_msgTypes,
	}.Build()
	File_api_proto_shortener_proto = out.File
	file_api_proto_shortener_proto_goTypes = nil
	file_api_proto_shortener_proto_depIdxs = nil
}
