// Code generated by reset generator. DO NOT EDIT.

package deleter

import (
	"sync"
)

// Reset сбрасывает состояние объекта Deleter к начальным значениям.
func (r *Deleter) Reset() {
	if resetter, ok := r.r.(interface{ Reset() }); ok && r.r != nil {
		resetter.Reset()
	} else {
		r.r = nil
	}
	r.inputCh = nil
	r.outputCh = nil
	r.wg = sync.WaitGroup{}
	r.stopCh = nil
	r.mu = sync.Mutex{}

	if r.buffer != nil {
		r.buffer = r.buffer[:0]
	}
	r.flushCh = nil
}
