// Code generated by reset generator. DO NOT EDIT.

package consumer

import (
	"net/http"
	"os"

	"golang.org/x/sync/errgroup"
)

// Reset сбрасывает состояние объекта Consumer к начальным значениям.
func (r *Consumer) Reset() {
	r.id = ""
	r.events = nil
	r.eg = errgroup.Group{}
	r.shutdown = nil
}

// Reset сбрасывает состояние объекта File к начальным значениям.
func (r *File) Reset() {
	r.Consumer = Consumer{}
	if r.file != nil {
		*r.file = os.File{}
	}
}

// Reset сбрасывает состояние объекта Remote к начальным значениям.
func (r *Remote) Reset() {
	r.Consumer = Consumer{}
	r.url = ""
	if r.client != nil {
		*r.client = http.Client{}
	}
}
