// Code generated by reset generator. DO NOT EDIT.

package auditor

import (
	"golang.org/x/sync/errgroup"
)

// Reset сбрасывает состояние объекта Auditor к начальным значениям.
func (r *Auditor) Reset() {
	clear(r.consumers)
	r.eg = errgroup.Group{}
	r.inputEvents = nil
	r.shutdown = nil
}
